using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DwarfApp
{
    public enum ErrCodes
    {
        RESULT_OK = 0,
        RESULT_CAM_OPENED = -1,
        RESULT_CAM_CLOSED = -2,
        RESULT_CAM_RECORDING = -3,
        RESULT_CAM_TAKING_PHOTO = -4,
        RESULT_MOTOR_RUNNING = -5,
        RESULT_MOTOR_STOPED = -6,
        RESULT_MOTOR_SEND_FAILED = -7,
        RESULT_PANORAMA_STARTED = -8,
        RESULT_MOTOR_ERROR_RUNNING = -9,
        RESULT_CAM_PAUSING_MUTILPHOTO = -10,
        RESULT_CAM_AUTO_FOCUSING = -11,
        RESULT_TRACKER_UNINIT = -12,
        RESULT_TRACKER_INITING = -13,
        RESULT_TRACKER_INITIED = -14,
        RESULT_TRACKER_TRACKING = -15,
        RESULT_OTA_STARTING = -16,
        RESULT_GOTO_JPGTOFITS_FAILED = -17,
        RESULT_GOTO_PLATE_SOLVING_FAILED = -18,
        RESULT_GOTO_CALIBRATION_FAILED = -19,
        RESULT_BLE_WIFI_CONFIGING = -20,
        RESULT_BLE_WIFI_CONFIGED = -21,
        RESULT_MOTOR_LIMIT = -22,
        RESULT_TFCARD_NOT_EXIST = -23,
        MOTOR_RESET_NOT_PERFORMED = -24,
        RESULT_OTA_ERR = -25,
        RESULT_OTA_ELE_LOW = -26,
        RESULT_OTA_VERSION_ERR = -27,
        RESULT_GOTO_PLATE_SOLVING = -28,
        RESULT_GOTO_CALIBRATING = -29,
        RESULT_GOTO_TRACKING = -30,
        RESULT_GOTO_STOPPING = -31,
        RESULT_OPEN_UVC_CAMERA_FAILED = -32,
        RESULT_UVC_CAMERA_CANNOT_FOUND = -33,
        RESULT_TRACKER_STOP = -34,
        RESULT_TL_RECORDING = -35,
        RESULT_AUTO_FOCUSING = -36,
        RESULT_BLE_PASSWORD_ERROR = -37,
        RESULT_WIFI_PASSWORD_ERROR = -38,
        RESULT_BLE_WIFI_CONFIG_ERROR = -39,
        RESULT_PANORAMAING = -40,
        RESULT_NO_DARK_FRAME = -41,
        RESULT_DARK_FRAME_ERROR = -42,
        RESULT_CAPTURE_RAW_ELE_LOW = -43,
        RESULT_CLOSING_CAM_TELE = -44,
        STATE_CALIBRATION_START = 1000,
        STATE_CALIBRATION_PLATE_SOLVING = 1001,
        STATE_CALIBRATION_FAILED = 1002,
        STATE_GOTO_START = 1003,
        STATE_GOTO_PLATE_SOLVING = 1004,
        STATE_GOTO_TRACKING = 1005,
        STATE_GOTO_FAILED = 1006,
        STATE_ASTRO_STOPPING = 1007,
        STATE_ASTRO_END = 1008,
        STATE_CALIBRATION_SUCCESS = 1009
    }

    public enum Motor
    {
        SPIN = 1,
        PITCH = 2,
    }
    
}
